<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\si_cat_municipios;

class cat_municipios extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
$data = [
     ["entidad_federativa_id"=>15,"cve_municipio"=>1,"municipio"=>"ACAMBAY","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>2,"municipio"=>"ACOLMAN","region_id"=>11]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>3,"municipio"=>"ACULCO","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>4,"municipio"=>"ALMOLOYA DE ALQUISIRAS","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>5,"municipio"=>"ALMOLOYA DE JUAREZ","region_id"=>6]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>6,"municipio"=>"ALMOLOYA DEL RIO","region_id"=>13]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>7,"municipio"=>"AMANALCO","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>8,"municipio"=>"AMATEPEC","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>9,"municipio"=>"AMECAMECA","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>10,"municipio"=>"APAXCO","region_id"=>20]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>11,"municipio"=>"ATENCO","region_id"=>15]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>12,"municipio"=>"ATIZAPAN","region_id"=>7]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>13,"municipio"=>"ATIZAPAN DE ZARAGOZA","region_id"=>4]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>14,"municipio"=>"ATLACOMULCO","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>15,"municipio"=>"ATLAUTLA","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>16,"municipio"=>"AXAPUSCO","region_id"=>11]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>17,"municipio"=>"AYAPANGO","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>18,"municipio"=>"CALIMAYA","region_id"=>13]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>19,"municipio"=>"CAPULHUAC","region_id"=>7]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>20,"municipio"=>"COACALCO DE BERRIOZABAL","region_id"=>18]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>21,"municipio"=>"COATEPEC HARINAS","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>22,"municipio"=>"COCOTITLAN","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>23,"municipio"=>"COYOTEPEC","region_id"=>14]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>24,"municipio"=>"CUAUTITLAN","region_id"=>18]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>25,"municipio"=>"CHALCO","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>26,"municipio"=>"CHAPA DE MOTA","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>27,"municipio"=>"CHAPULTEPEC","region_id"=>8]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>28,"municipio"=>"CHIAUTLA","region_id"=>11]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>29,"municipio"=>"CHICOLOAPAN","region_id"=>3]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>30,"municipio"=>"CHICONCUAC","region_id"=>15]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>31,"municipio"=>"CHIMALHUACAN","region_id"=>3]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>32,"municipio"=>"DONATO GUERRA","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>33,"municipio"=>"ECATEPEC DE MORELOS","region_id"=>5]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>34,"municipio"=>"ECATZINGO","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>35,"municipio"=>"HUEHUETOCA","region_id"=>20]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>36,"municipio"=>"HUEYPOXTLA","region_id"=>20]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>37,"municipio"=>"HUIXQUILUCAN","region_id"=>9]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>38,"municipio"=>"ISIDRO FABELA","region_id"=>9]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>39,"municipio"=>"IXTAPALUCA","region_id"=>3]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>40,"municipio"=>"IXTAPAN DE LA SAL","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>41,"municipio"=>"IXTAPAN DEL ORO","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>42,"municipio"=>"IXTLAHUACA","region_id"=>6]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>43,"municipio"=>"XALATLACO","region_id"=>7]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>44,"municipio"=>"JALTENCO","region_id"=>14]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>45,"municipio"=>"JILOTEPEC","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>46,"municipio"=>"JILOTZINGO","region_id"=>9]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>47,"municipio"=>"JIQUIPILCO","region_id"=>6]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>48,"municipio"=>"JOCOTITLAN","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>49,"municipio"=>"JOQUICINGO","region_id"=>13]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>50,"municipio"=>"JUCHITEPEC","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>51,"municipio"=>"LERMA","region_id"=>7]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>52,"municipio"=>"MALINALCO","region_id"=>13]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>53,"municipio"=>"MELCHOR OCAMPO","region_id"=>14]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>54,"municipio"=>"METEPEC","region_id"=>8]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>55,"municipio"=>"MEXICALTZINGO","region_id"=>8]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>56,"municipio"=>"MORELOS","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>57,"municipio"=>"NAUCALPAN DE JUAREZ","region_id"=>9]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>58,"municipio"=>"NEZAHUALCOYOTL","region_id"=>10]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>59,"municipio"=>"NEXTLALPAN","region_id"=>14]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>60,"municipio"=>"NICOLAS ROMERO","region_id"=>4]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>61,"municipio"=>"NOPALTEPEC","region_id"=>11]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>62,"municipio"=>"OCOYOACAC","region_id"=>7]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>63,"municipio"=>"OCUILAN","region_id"=>13]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>64,"municipio"=>"EL ORO","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>65,"municipio"=>"OTUMBA","region_id"=>11]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>66,"municipio"=>"OTZOLOAPAN","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>67,"municipio"=>"OTZOLOTEPEC","region_id"=>6]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>68,"municipio"=>"OZUMBA","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>69,"municipio"=>"PAPALOTLA","region_id"=>11]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>70,"municipio"=>"LA PAZ","region_id"=>3]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>71,"municipio"=>"POLOTITLAN","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>72,"municipio"=>"RAYON","region_id"=>13]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>73,"municipio"=>"SAN ANTONIO LA ISLA","region_id"=>13]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>74,"municipio"=>"SAN FELIPE DEL PROGRESO","region_id"=>6]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>75,"municipio"=>"SAN MARTIN DE LAS PIRAMIDES","region_id"=>11]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>76,"municipio"=>"SAN MATEO ATENCO","region_id"=>8]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>77,"municipio"=>"SAN SIMON DE GUERRERO","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>78,"municipio"=>"SANTO TOMAS","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>79,"municipio"=>"SOYANIQUILPAN DE JUAREZ","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>80,"municipio"=>"SULTEPEC","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>81,"municipio"=>"TECAMAC","region_id"=>5]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>82,"municipio"=>"TEJUPILCO","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>83,"municipio"=>"TEMAMATLA","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>84,"municipio"=>"TEMASCALAPA","region_id"=>11]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>85,"municipio"=>"TEMASCALCINGO","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>86,"municipio"=>"TEMASCALTEPEC","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>87,"municipio"=>"TEMOAYA","region_id"=>6]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>88,"municipio"=>"TENANCINGO","region_id"=>13]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>89,"municipio"=>"TENANGO DEL AIRE","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>90,"municipio"=>"TENANGO DEL VALLE","region_id"=>13]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>91,"municipio"=>"TEOLOYUCAN","region_id"=>14]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>92,"municipio"=>"TEOTIHUACAN","region_id"=>11]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>93,"municipio"=>"TEPETLAOXTOC","region_id"=>11]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>94,"municipio"=>"TEPETLIXPA","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>95,"municipio"=>"TEPOTZOTLAN","region_id"=>14]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>96,"municipio"=>"TEQUIXQUIAC","region_id"=>20]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>97,"municipio"=>"TEXCALTITLAN","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>98,"municipio"=>"TEXCALYACAC","region_id"=>7]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>99,"municipio"=>"TEXCOCO","region_id"=>15]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>100,"municipio"=>"TEZOYUCA","region_id"=>15]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>101,"municipio"=>"TIANGUISTENCO","region_id"=>7]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>102,"municipio"=>"TIMILPAN","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>103,"municipio"=>"TLALMANALCO","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>104,"municipio"=>"TLALNEPANTLA DE BAZ","region_id"=>16]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>105,"municipio"=>"TLATLAYA","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>106,"municipio"=>"TOLUCA","region_id"=>17]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>107,"municipio"=>"TONATICO","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>108,"municipio"=>"TULTEPEC","region_id"=>18]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>109,"municipio"=>"TULTITLAN","region_id"=>18]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>110,"municipio"=>"VALLE DE BRAVO","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>111,"municipio"=>"VILLA DE ALLENDE","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>112,"municipio"=>"VILLA DEL CARBON","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>113,"municipio"=>"VILLA GUERRERO","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>114,"municipio"=>"VILLA VICTORIA","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>115,"municipio"=>"XONACATLAN","region_id"=>9]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>116,"municipio"=>"ZACAZONAPAN","region_id"=>19]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>117,"municipio"=>"ZACUALPAN","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>118,"municipio"=>"ZINACANTEPEC","region_id"=>17]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>119,"municipio"=>"ZUMPAHUACAN","region_id"=>13]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>120,"municipio"=>"ZUMPANGO","region_id"=>20]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>121,"municipio"=>"CUAUTITLAN IZCALLI","region_id"=>4]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>122,"municipio"=>"VALLE DE CHALCO SOLIDARIDAD","region_id"=>1]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>123,"municipio"=>"LUVIANOS","region_id"=>12]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>124,"municipio"=>"SAN JOSE DEL RINCON","region_id"=>2]
    ,["entidad_federativa_id"=>15,"cve_municipio"=>125,"municipio"=>"TONANITLA","region_id"=>14]
        ];



        foreach($data as $key => $value){
            si_cat_municipios::create($value);
        }

    }
}
