<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Catalogos\Cedis as CedisModel;


class cedis extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["id" => 1, "nombre" => "001 AMECAMECA", "municipio_id" => 9, "direccion" => "C. OCAMPO #132, BARRIO SAN JUAN, AMECAMECA, C.P. 56900", "capacidad" => 0],
            ["id" => 5, "nombre" => "005 ATLAUTLA", "municipio_id" => 15, "direccion" => "C. ZARAGOZA S/N, BARRIO SAN MARTIN, ATLAUTLA, C.P. 56970", "capacidad" => 0],
            ["id" => 2, "nombre" => "002 AYAPANGO", "municipio_id" => 17, "direccion" => "CAMINO REAL S/N, BARRIO SOLEDAD, AYAPANGO, C.P. 56760", "capacidad" => 0],
            ["id" => 6, "nombre" => "006 JUCHITEPEC", "municipio_id" => 50, "direccion" => "MORELOS S/N, BARRIO JUCHI, JUCHITEPEC, C.P. 56860", "capacidad" => 0],
            ["id" => 7, "nombre" => "007 OZUMBA", "municipio_id" => 68, "direccion" => "AV. JUÁREZ #28 - A, CENTRO, OZUMBA, C.P. 56800", "capacidad" => 0],
            ["id" => 3, "nombre" => "003 TEPETLIXPA", "municipio_id" => 94, "direccion" => "AV. 20 DE NOVIEMBRE #21, TEPETLIXPA, C.P. 56880", "capacidad" => 0],
            ["id" => 4, "nombre" => "004 TLALMANALCO", "municipio_id" => 103, "direccion" => "C. GUERRERO #41, TLALMANALCO, C.P. 56700", "capacidad" => 0],
            ["id" => 8, "nombre" => "008 EJIDO DE BOMBATEVI", "municipio_id" => 14, "direccion" => "ATLACOMULCO,EL JAZMÍN SALIDA A SAN JUAN DE LOS JARROS, BOMBATEVI, ATLACOMULCO, C.P. 50486", "capacidad" => 0],
            ["id" => 9, "nombre" => "009 SAN FRANCISCO CHALCHIHUAPAN", "municipio_id" => 14, "direccion" => "AV. NUEVO SAN FRANCISCO S/N, SAN FRANCISCO CHALCHIHUAPAN, ATLACOMULCO,C.P. 50480", "capacidad" => 0],
            ["id" => 10, "nombre" => "010 EL ORO", "municipio_id" => 64, "direccion" => "BLVD. JACINTO SALINAS S/N, COL. EL LIBRAMIENTO, EL ORO, C.P. 50600", "capacidad" => 0],
            ["id" => 173, "nombre" => "173 SAN PEDRO DE LOS BAÑOS", "municipio_id" => 42, "direccion" => "A UN COSTADO DE LA DELEGACION SAN PEDRO DE LOS BAÑOS CENTRO.", "capacidad" => 0],
            ["id" => 204, "nombre" => "204 SANTA ANA IXTLAHUACA", "municipio_id" => 42, "direccion" => "DOMICILIO CONOCIDO, A ESPALDAS DEL JARDIN DE NIÑOS AGUSTIN YAÑEZ, SANTA ANA IXTLAHUACA, IXTLAHUACA, C.P. 50760", "capacidad" => 0],
            ["id" => 11, "nombre" => "011 JIQUIPILCO", "municipio_id" => 47, "direccion" => "JIQUIPILCO CENTRO, SOBRE CALLE FRANCISCO VILLA, C.P. 50800", "capacidad" => 0],
            ["id" => 12, "nombre" => "012 JOCOTITLÁN", "municipio_id" => 48, "direccion" => "PRIVADA RIVA PALACIO S/N, COL. CENTRO, JOCOTITLAN, C.P. 50700", "capacidad" => 0],
            ["id" => 14, "nombre" => "014 NUEVA SAN ANTONIO", "municipio_id" => 25, "direccion" => "LA QUEBRADA MZ91 LT23 ESQ. BRONCE, NUEVA SAN ANTONIO, CHALCO, C.P. 56605", "capacidad" => 0],
            ["id" => 13, "nombre" => "013 SANTA CATARINA AYOTZINGO", "municipio_id" => 25, "direccion" => "5 DE FEBRERO #43,ENTRE 2 DE ABRIL Y 5 DE FEBRERO, SANTA CATARINA AYOTZINGO, C.P. 56623", "capacidad" => 0],
            ["id" => 15, "nombre" => "015 SAN MARTIN CUAUTLALPAN", "municipio_id" => 25, "direccion" => "AV. REVOLUCIÓN S/N ESQ. BENITO JUAREZ, SAN MARTIN CUATLALPAN. C.P. 56644", "capacidad" => 0],
            ["id" => 17, "nombre" => "017 COCOTITLÁN", "municipio_id" => 22, "direccion" => "C. ZARAGOZA #14, AYOTEPEC, COCOTITLAN,C.P. 56680 ", "capacidad" => 0],
            ["id" => 18, "nombre" => "018 TEMAMATLA", "municipio_id" => 83, "direccion" => "YUCATAN S/N, BAJA CALIFORNIA Y SONORA, SAN JUAN TEMAMATLA, TEMAMATLA, C.P. 56650", "capacidad" => 0],
            ["id" => 201, "nombre" => "201 CHIMALHUACAN", "municipio_id" => 31, "direccion" => "CERRADA SALINAS S/N PROLONGACION ALDAMA ENTRE ABASOLO Y CORREGIDORA,CABECERA MUNICIPAL, CHIMALHUACAN, C.P. 56330", "capacidad" => 0],
            ["id" => 169, "nombre" => "169 ADOLFO LÓPEZ MATEOS", "municipio_id" => 13, "direccion" => "QUERETARO #9, COL .ADOLFO LOPEZ MATEOS SECCION MARIA LUISA, ATIZAPAN DE ZARAGOZA, C.P.52910", "capacidad" => 0],
            ["id" => 21, "nombre" => "021 CERRO GRANDE", "municipio_id" => 13, "direccion" => "MOCTEZUMA #23, COL. CERRO GRANDE, ATIZAPAN DE ZARAGOZA, C.P.52920", "capacidad" => 0],
            ["id" => 22, "nombre" => "022 ALFREDO V BONFIL", "municipio_id" => 13, "direccion" => "20 DE NOVIEMBRE LT. 8 MZ. 42, COL, ALFREDO V BONFIL, ATIZAPAN DE ZARAGOZA, C.P. 52940", "capacidad" => 0],
            ["id" => 20, "nombre" => "020 MÉXICO 86", "municipio_id" => 13, "direccion" => "FRANCIA 77, COL. MEXICO 86, ATIZAPAN DE ZARAGOZA, C.P. 52915", "capacidad" => 0],
            ["id" => 170, "nombre" => "170 BOSQUES DE ATIZAPAN", "municipio_id" => 13, "direccion" => "CALLE 5 #21, COL. BOSQUES DE ATIZAPAN, ATIZAPAN DE ZARAGOZA , C.P.52976", "capacidad" => 0],
            ["id" => 198, "nombre" => "198 ALFREDO V BONFIL", "municipio_id" => 13, "direccion" => "CAMINO REAL #17, COL ALFREDO V BONFIL, ATIZAPAN DE ZARAGOZA, C.P. 52940", "capacidad" => 0],
            ["id" => 23, "nombre" => "023 SAN LORENZO TETLIXTAC", "municipio_id" => 20, "direccion" => "C. NIÑOS HEROES #55 INTERIOR A, SAN LORENZO TETLIXTAC, COACALCO DE BERRIOZABAL, C.P. 55714", "capacidad" => 0],
            ["id" => 24, "nombre" => "024 SAN LORENZO TETLIXTAC", "municipio_id" => 20, "direccion" => "C. NIÑOS HEROES #55 INTERIOR B, SAN LORENZO TETLIXTAC, COACALCO DE BERRIOZABAL, C.P. 55714", "capacidad" => 0],
            ["id" => 25, "nombre" => "025 COYOTEPEC", "municipio_id" => 23, "direccion" => "C.SAN CRISTOBAL S/N, BO. CABECERA, COYOTEPEC, C.P. 54660", "capacidad" => 0],
            ["id" => 26, "nombre" => "026 CUAUTITLÁN", "municipio_id" => 24, "direccion" => "EMILIANO ZAPATA MZ 12 LT6, COL. LAZARO CARDENAS, CUAUTITLÁN, C.P.54870", "capacidad" => 0],
            ["id" => 27, "nombre" => "027 MELCHOR OCAMPO", "municipio_id" => 53, "direccion" => "GABRIEL RAMOS MILLÁN #831, SEÑOR DE LOS MILAGROS, MELCHOR OCAMPO, C.P. 54884", "capacidad" => 0],
            ["id" => 174, "nombre" => "174 TEOLOYUCAN", "municipio_id" => 91, "direccion" => "C. NUEVO LEÓN # 22, ZIMAPAN, TEOLOYUCAN, C.P. 54786", "capacidad" => 0],
            ["id" => 175, "nombre" => "175 TEPOTZOTLÁN", "municipio_id" => 95, "direccion" => "AV. LIC. BENITO JUAREZ #32-26, COL. TLACATECO, TEPOTZOTLAN, C.P. 54605", "capacidad" => 0],
            ["id" => 29, "nombre" => "029 VALLE DE LAS FLORES", "municipio_id" => 121, "direccion" => "MIGUEL HIDALGO #105, COL.VALLE DE LAS FLORES, CUAUTITLÁN IZCALLI, C.P. 54744", "capacidad" => 0],
            ["id" => 30, "nombre" => "030 JARDINES DE LA HACIENDA", "municipio_id" => 121, "direccion" => "AV. DEL MOLINO #104, COL. JARDINES DE LA HACIENDA, CUAUTITLÁN IZCALLI, C.P. 54729", "capacidad" => 0],
            ["id" => 28, "nombre" => "028 LA PIEDAD", "municipio_id" => 121, "direccion" => "CERRADA DE TOMAS URBINA LT. 13 MZ.4, COL. LA PIEDAD, CUAUTITLAN IZCALLI, C.P. 54720", "capacidad" => 0],
            ["id" => 208, "nombre" => "208 LA PRESITA", "municipio_id" => 121, "direccion" => "C. AZUL #13, LA PRESITA, CUAUTITLÁN IZCALLI, 54763", "capacidad" => 0],
            ["id" => 33, "nombre" => "033 SANTO TOMAS", "municipio_id" => 33, "direccion" => "CIRCUITO CUAUHTEMOC ESQ.  CALLE HERRERIA, LOCAL A LOTE 2 S/N,COL. SANTO TOMAS, CHICONAUTLA, C.P. 55066", "capacidad" => 0],
            ["id" => 35, "nombre" => "035 EJIDAL EMILIANO ZAPATA", "municipio_id" => 33, "direccion" => "AV. REVOLUCIÓN MZ25 LT1, ZONA 6, EJIDAL EMILIANO ZAPATA, ECATEPEC DE MORELOS C.P. 55024", "capacidad" => 0],
            ["id" => 32, "nombre" => "032 EJIDOS DE SAN CRISTÓBAL", "municipio_id" => 33, "direccion" => "BONSAI MZ1 LT2, EJIDOS DE SAN CRISTOBAL, ECATEPEC DE MORELOS, C.P. 55024", "capacidad" => 0],
            ["id" => 36, "nombre" => "036 JARDINES DE MORELOS", "municipio_id" => 33, "direccion" => "BOSQUE DE CAOBA #2, MZ.207 LT.33, JARDINES DE MORELOS, ECATEPEC DE MORELOS, C.P. 55070", "capacidad" => 0],
            ["id" => 31, "nombre" => "031 SAN CRISTÓBAL CENTRO", "municipio_id" => 33, "direccion" => "AGRICULTURA #97, ABASOLO Y MELCHOR OCAMPO, SAN CRISTOBAL CENTRO, ECATEPEC DE MORELOS, C.P. 55000", "capacidad" => 0],
            ["id" => 34, "nombre" => "034 SANTA CLARA COATITLA", "municipio_id" => 33, "direccion" => "CALLE AZTECAS #346 SANTA CLARA COATITLA ECATEPEC DE MORELOS CP 55540", "capacidad" => 0],
            ["id" => 176, "nombre" => "176 SAUCES 1", "municipio_id" => 33, "direccion" => "JOSE ORTIZ DE DOMINGUEZ #67, COL. SAUCES 1, ECATEPEC DE MORELOS, C.P. 55269", "capacidad" => 0],
            ["id" => 40, "nombre" => "040 MAGDALENA CHICHICASPA", "municipio_id" => 37, "direccion" => "GOLONDRINAS KM 65, CARR. HUIXQUILUCAN-NAUCALPAN, LA MAGDALENA CHICHICASPA, HUIXQUILUCAN, C.P. 52796", "capacidad" => 0],
            ["id" => 37, "nombre" => "037 JESUS DEL MONTE", "municipio_id" => 37, "direccion" => "JOSE MA. MORELOS Y PAVON #27, COL. JESUS DEL MONTE, HUIXQUILUCAN, C.P.52764", "capacidad" => 0],
            ["id" => 41, "nombre" => "041 SAN MARTIN", "municipio_id" => 37, "direccion" => "20 DE NOVIEMBRE #7, BARR. SAN MARTIN, HUIXQUILUCAN, C.P. 52767", "capacidad" => 0],
            ["id" => 38, "nombre" => "038 JILOTZINGO", "municipio_id" => 46, "direccion" => "CARRETERA NAUCALPAN -IXTLAHUACA SAN LUIS AYUCAN SN,  A UN COSTADO DE LA REFACCIONARIA SOLANO, JILOTZINGO, C.P. 54570", "capacidad" => 0],
            ["id" => 203, "nombre" => "203 OTZOLOTEPEC", "municipio_id" => 67, "direccion" => "LA PURISIMA #24, COL. LA PURISIMA, OTZOLOTEPEC, C.P. 52080", "capacidad" => 0],
            ["id" => 39, "nombre" => "039 XONACATLÁN", "municipio_id" => 115, "direccion" => "FRANCISCO SARABIA #12,CENTRO, XONACATLAN, C.P. 52060", "capacidad" => 0],
            ["id" => 42, "nombre" => "042 SANTA BARBARA", "municipio_id" => 39, "direccion" => "AV ACOZAC. 1, SANTA BARBARA, IXTAPALUCA, C.P. 56538", "capacidad" => 0],
            ["id" => 209, "nombre" => "209 SANTA CRUZ TLALPIZAHUAC", "municipio_id" => 39, "direccion" => "CARR. FEDERAL MÉXICO-PUEBLA MZA16 LOTE 17, SANTA CRUZ TLALPIZAHUAC, IXTAPALUCA, C.P. 56576", "capacidad" => 0],
            ["id" => 54, "nombre" => "054 ACAMBAY DE RUIZ CASTAÑEDA", "municipio_id" => 1, "direccion" => "C. 16 DE SEPTIEMBRE 105-107, CENTRO, ACAMBAY DE RUIZ CASTAÑEDA, C.P. 50300", "capacidad" => 0],
            ["id" => 46, "nombre" => "046 ACULCO", "municipio_id" => 3, "direccion" => "JOSE SANCHEZ LARA S/N, CENTRO, ACULCO, C.P. 50360", "capacidad" => 0],
            ["id" => 47, "nombre" => "047 CHAPA DE MOTA", "municipio_id" => 26, "direccion" => "C. SIN NOMBRE, TENJAY, CHAPA DE MOTA, C.P. 54373", "capacidad" => 0],
            ["id" => 48, "nombre" => "048 JILOTEPEC", "municipio_id" => 45, "direccion" => "C. CULTURA OTOMI S/N, CANALEJAS, JILOTEPEC, C.P. 54260", "capacidad" => 0],
            ["id" => 49, "nombre" => "049 MORELOS", "municipio_id" => 56, "direccion" => "C. DR.JORGE JIMENEZ CANTU, A UN COSTADO DEL MERCADO NUEVO, SAN BARTOLO MORELOS, MORELOS, C.P. 50550", "capacidad" => 0],
            ["id" => 50, "nombre" => "050 POLOTITLÁN", "municipio_id" => 71, "direccion" => "C. CUITLAHUAC SN, CENTRO, POLOTITLAN, C.P.54200", "capacidad" => 0],
            ["id" => 51, "nombre" => "051 SOYANIQUILPAN DE JUÁREZ", "municipio_id" => 79, "direccion" => "LOS MUERTOS #19, SAN FRANCISCO SOYANIQUILPAN, SOYANIQUILPAN DE JUAREZ, C.P. 54280", "capacidad" => 0],
            ["id" => 55, "nombre" => "055 TEMASCALCINGO", "municipio_id" => 85, "direccion" => "3ERA CERRADA JOSE MARÍA VELASCO S/N, BARRIO DE BONSHO, TEMASCALCINGO, C.P.50410", "capacidad" => 0],
            ["id" => 52, "nombre" => "052 TIMILPAN", "municipio_id" => 102, "direccion" => "VENUSTIANO CARRANZA ESQ. FRANCISCO I. MADERO S/N, COLONIA CENTRO, TIMILPAN, C.P. 50500", "capacidad" => 0],
            ["id" => 53, "nombre" => "053 VILLA DEL CARBÓN", "municipio_id" => 112, "direccion" => "CERCA DE MANZANA 033, SAN JERONIMO ZACAPEXCO, VILLA DEL CARBÓN, C.P.54310", "capacidad" => 0],
            ["id" => 56, "nombre" => "056 ALMOLOYA DEL RÍO", "municipio_id" => 6, "direccion" => "MANUEL BERNAL #8 ORIENTE ESQ.  IGNACIO MANUEL ALTAMIRANO, ALMOLOYA DEL RÍO, C.P.52540", "capacidad" => 0],
            ["id" => 57, "nombre" => "057 ATIZAPÁN", "municipio_id" => 12, "direccion" => "AV. ACUEDUCTO #114, SANTA CRUZ ATIZAPAN, ATIZAPAN, C.P 52500 ", "capacidad" => 0],
            ["id" => 58, "nombre" => "058 CAPULHUAC", "municipio_id" => 19, "direccion" => "AV. PORFIRIO DIAZ #504, CAPULHUAC, C.P 52700", "capacidad" => 0],
            ["id" => 64, "nombre" => "064 GUADALUPE VICTORIA", "municipio_id" => 51, "direccion" => "VALLE ESCONDIDO S/N, COL. GUADALUPE VICTORIA, LERMA, C.P.  52050", "capacidad" => 0],
            ["id" => 65, "nombre" => "065 SAN JOSE EL LLANITO", "municipio_id" => 51, "direccion" => "C. 5 DE MAYO #3, SAN JOSE EL LLANITO, LERMA, C.P. 52004", "capacidad" => 0],
            ["id" => 59, "nombre" => "059 OCOYOACAC", "municipio_id" => 62, "direccion" => "AV CUAUHTÉMOC # 33 ESQ. MICHOACÁN, TEPEXOYUCA, OCOYOACAC. CP 52755", "capacidad" => 0],
            ["id" => 60, "nombre" => "060 OCUILAN", "municipio_id" => 63, "direccion" => "CALLE REFORMA S/N, SANTA MONICA, OCUILAN, C.P. 52484", "capacidad" => 0],
            ["id" => 61, "nombre" => "061 TEXCALYACAC", "municipio_id" => 98, "direccion" => "PUEBLA #3, MEXICAPAN, TEXCALYACAC, C.P.52570", "capacidad" => 0],
            ["id" => 62, "nombre" => "062 TIANGUISTENCO", "municipio_id" => 101, "direccion" => "JOSE MARIA MORELOS #321, CENTRO, TIANGUISTENCO, C.P.52600", "capacidad" => 0],
            ["id" => 63, "nombre" => "063 XALATLACO", "municipio_id" => 43, "direccion" => "AVENIDA 16 DE SEPTIEMBRE # 1 COL. CENTRO, XALATLACO, C.P.52680", "capacidad" => 0],
            ["id" => 67, "nombre" => "067 LA PAZ", "municipio_id" => 70, "direccion" => "RIO BALSAS Y RIO BALUARTE MZ 31 LT 2, EL SALADO, LA PAZ, C.P. 56524", "capacidad" => 0],
            ["id" => 68, "nombre" => "068 CALIMAYA", "municipio_id" => 18, "direccion" => "MIGUEL HIDALGO # 38, CALIMAYA, C.P. 52200", "capacidad" => 0],
            ["id" => 69, "nombre" => "069 CHAPULTEPEC", "municipio_id" => 27, "direccion" => "JUAREZ # 510, ENTRE ALDAMA Y RAYÓN,CENTRO,  CHAPULTEPEC, C.P 52240", "capacidad" => 0],
            ["id" => 70, "nombre" => "070 METEPEC", "municipio_id" => 54, "direccion" => "MIGUEL HIDALGO # 128 , ENTRE MATAMOROS Y EZEQUIEL CAPISTRAN, BARRIO SAN MATEO, METEPEC, CP. 52140", "capacidad" => 0],
            ["id" => 72, "nombre" => "072 MEXICALTZINGO", "municipio_id" => 55, "direccion" => "EMILIANO ZAPATA #207 A, CASI ESQUINA REVOLUCIÓN, MEXICALTZINGO, C.P 52180", "capacidad" => 0],
            ["id" => 73, "nombre" => "073 SAN ANTONIO LA ISLA", "municipio_id" => 73, "direccion" => "ADOLFO LOPEZ MATEOS SN, ENTRE JUAN ALDAMA E HIDALGO, SAN LUCAS TEPEMAJALCO, SAN ANTONIO LA ISLA, C.P 52280", "capacidad" => 0],
            ["id" => 74, "nombre" => "074 SAN MATEO ATENCO", "municipio_id" => 76, "direccion" => "HERMENEGILDO GALENA # 1, CASI ESQUINA BUENAVISTA, BARRIO LA CONCEPCIÓN, SAN MATEO ATENCO, C.P 52104", "capacidad" => 0],
            ["id" => 196, "nombre" => "196 LA LUNA", "municipio_id" => 57, "direccion" => "ZARAGOZA #10, LOS REMEDIOS, NAUCALPAN DE JUAREZ, C.P.53410", "capacidad" => 0],
            ["id" => 197, "nombre" => "197 ADOLFO LOPEZ MATEOS", "municipio_id" => 57, "direccion" => "CALZADA DE LOS REMEDIOS 1-41, ADOLFO LOPEZ MATEOS, NAUCALPAN DE JUÁREZ, C.P. 53410", "capacidad" => 0],
            ["id" => 177, "nombre" => "177 SAN ANTONIO ZOMEYUCAN", "municipio_id" => 57, "direccion" => "AV CENTENARIO #95, SAN ANTONIO ZOMEYUCAN, NAUCALPAN DE JUÁREZ, C.P.53750", "capacidad" => 0],
            ["id" => 77, "nombre" => "077 NEZAHUALCOYOTL BENITO JUAREZ", "municipio_id" => 58, "direccion" => "JUAN COLORADO #29, BENITO JUAREZ, NEZAHUALCÓYOTL, C.P.57000", "capacidad" => 0],
            ["id" => 78, "nombre" => "078 SAN AGUSTIN", "municipio_id" => 58, "direccion" => "VENUSTIANO CARRANZA ESQ. OTILIO MONTAÑO S/N, COL SAN AGUSTIN, NEZAHUALCÓYOTL, C.P. 56344", "capacidad" => 0],
            ["id" => 79, "nombre" => "079 LAS FUENTES", "municipio_id" => 58, "direccion" => "HIDALGO #320, COL. LAS FUENTES, NEZAHUALCÓYOTL, C.P.57600", "capacidad" => 0],
            ["id" => 80, "nombre" => "080 BENITO JUAREZ", "municipio_id" => 58, "direccion" => "CALLE FLOR #11, COL. BENITO JUAREZ, NEZAHUALCOYOTL, C.P. 57000", "capacidad" => 0],
            ["id" => 81, "nombre" => "081 METROPOLITANA", "municipio_id" => 58, "direccion" => "MONUMENTO A LA RAZA #199, METROPOLITANA, NEZAHUALCÓYOTL, C.P.57740", "capacidad" => 0],
            ["id" => 82, "nombre" => "082 TAMAULIPAS", "municipio_id" => 58, "direccion" => "DALIA #133, TAMAULIPAS, NEZAHUALCÓYOTL, C.P. 57300", "capacidad" => 0],
            ["id" => 83, "nombre" => "083 VALLE DE ARAGON PRIMERA SECCIÓN", "municipio_id" => 58, "direccion" => "VALLE DE HUALLAGA #43, VALLE DE ARAGON PRIMERA SECCION, NEZAHUALCÓYOTL, C.P. 57100", "capacidad" => 0],
            ["id" => 195, "nombre" => "195 EVOLUCION", "municipio_id" => 58, "direccion" => "INDIOS VERDES #316, EVOLUCION, NEZAHUALCÓYOTL, C.P. 57700", "capacidad" => 0],
            ["id" => 199, "nombre" => "199 JUAREZ PANTITLAN", "municipio_id" => 58, "direccion" => "FRANCISCO I MADERO #156, COL. JUAREZ PANTITLAN, NEZAHUALCÓYOTL, C.P. 57460", "capacidad" => 0],
            ["id" => 85, "nombre" => "085 ISIDRO FABELA", "municipio_id" => 38, "direccion" => "CARR A MONTE ALTO S/N, EJIDO MIRAFLORES, ISIDRO FABELA, C.P. 54480", "capacidad" => 0],
            ["id" => 194, "nombre" => "194 NICOLÁS ROMERO", "municipio_id" => 60, "direccion" => "JAIME NUNÓ #1, COL. HIMNO NACIONAL, NICOLÁS ROMERO, C.P. 54434", "capacidad" => 0],
            ["id" => 86, "nombre" => "086 LOMAS DE TECAMAC", "municipio_id" => 81, "direccion" => "CALLE OLIVOS MZ. KK LT.3, LOMAS DE TECAMAC, TECAMAC, C.P. 55765", "capacidad" => 0],
            ["id" => 207, "nombre" => "207 TECAMAC CENTRO", "municipio_id" => 81, "direccion" => "ROSARIO #16, CENTRO, TECAMAC, C.P. 55740", "capacidad" => 0],
            ["id" => 88, "nombre" => "088 DONATO GUERRA", "municipio_id" => 32, "direccion" => "AV. PRINCIPAL SAN AGUSTÍN DE LAS PALMAS, DONATO GUERRA, C.P. 51030", "capacidad" => 0],
            ["id" => 89, "nombre" => "089 SAN FELIPE DEL PROGRESO", "municipio_id" => 74, "direccion" => "AV. MARIPOSA MONARCA ESQ. CALLE DE LA PAZ S/N, COL. CENTRO, SAN FELIPE DEL PROGRESO, C.P.50640", "capacidad" => 0],
            ["id" => 92, "nombre" => "092 BARRIO EL LLANO", "municipio_id" => 124, "direccion" => "LOC. LLANO SAN JUAN PALO SECO,  SAN JOSE DEL RINCON,C.P. 50670", "capacidad" => 0],
            ["id" => 200, "nombre" => "200 SAN ONOFRE", "municipio_id" => 124, "direccion" => "GUADALUPE DEL PEDREGAL S/N, SAN ONOFRE, SAN JOSÉ DEL RINCÓN, C.P. 50663", "capacidad" => 0],
            ["id" => 90, "nombre" => "090 VILLA DE ALLENDE", "municipio_id" => 111, "direccion" => "DOMICILIO CONOCIDO SIN CALLE,SIN NÚMERO, EL JACAL, VILLA DE ALLENDE, C.P. 51015", "capacidad" => 0],
            ["id" => 91, "nombre" => "091 VILLA VICTORIA", "municipio_id" => 114, "direccion" => "DOMICILIO CONOCIDO SIN NÚMERO, EL ESPINAL , VILLA VICTORIA, C.P.50985", "capacidad" => 0],
            ["id" => 93, "nombre" => "093 ALMOLOYA DE ALQUISIRAS", "municipio_id" => 4, "direccion" => "C. FILIBERTO GOMEZ S/N, COL. PRIMERA MANZANA, ALMOLOYA DE ALQUISIRAS, C.P. 51860", "capacidad" => 0],
            ["id" => 94, "nombre" => "094 AMANALCO", "municipio_id" => 7, "direccion" => "ZARAGOZA #96, COL. CENTRO, AMANALCO, C.P. 51260", "capacidad" => 0],
            ["id" => 95, "nombre" => "095 PALMAR CHICO", "municipio_id" => 8, "direccion" => "C. EMILIANO ZAPATA #13, PALMAR CHICO, AMATEPEC, C.P.51530", "capacidad" => 0],
            ["id" => 96, "nombre" => "096 AMATEPEC CENTRO", "municipio_id" => 8, "direccion" => "C. MIGUEL HIDALGO #9, COLONIA CENTRO, AMATEPEC, C.P. 51500", "capacidad" => 0],
            ["id" => 98, "nombre" => "098 IXTAPAN DEL ORO", "municipio_id" => 41, "direccion" => "AV. LIBERTAD S/N, COLONIA CENTRO, IXTAPAN DEL ORO, C.P.51070", "capacidad" => 0],
            ["id" => 99, "nombre" => "099 LUVIANOS", "municipio_id" => 123, "direccion" => "AV. 16 DE SEPTIEMBRE 17, ESQ. TLAXCALA, LUVIANOS, C.P. 51440", "capacidad" => 0],
            ["id" => 100, "nombre" => "100 OTZOLOAPAN", "municipio_id" => 66, "direccion" => "C. ISIDRO FABELA S/N, COLONIA CENTRO, OTZOLOAPAN, C.P. 51130 ", "capacidad" => 0],
            ["id" => 101, "nombre" => "101 SAN SIMON DE GUERRERO", "municipio_id" => 77, "direccion" => "DESVIACION SAN DIEGO CUENTLA, CARR TOLUCA-ALTAMIRANO KM 83.5, SAN SIMON DE GUERRERO, C.P. 51480", "capacidad" => 0],
            ["id" => 102, "nombre" => "102 SANTO TOMÁS", "municipio_id" => 78, "direccion" => "ZACATECAS ESQ. MORELOS S/N, COL. CENTRO, SANTO TOMÁS, C.P.51110", "capacidad" => 0],
            ["id" => 103, "nombre" => "103 SULTEPEC", "municipio_id" => 80, "direccion" => "BARRIO DE TEMOAYA S/N, COL. LA CUADRILLA, SULTEPEC,C.P. 51600 ", "capacidad" => 0],
            ["id" => 104, "nombre" => "104 VICENTE GUERRERO", "municipio_id" => 82, "direccion" => "C. PLUTARCO ELIAS CALLES S/N, COL. VICENTE GUERRERO, TEJUPILCO, C.P. 51412", "capacidad" => 0],
            ["id" => 182, "nombre" => "182 BEJUCOS", "municipio_id" => 82, "direccion" => "C.SILVANO SANCHEZ LOVERA S/N, COLONIA CENTRO, LOCALIDAD BEJUCOS, TEJUPILCO, CP 51430", "capacidad" => 0],
            ["id" => 183, "nombre" => "183 SAN FRANCISCO OXTOTILPAN", "municipio_id" => 86, "direccion" => "DOMICILIO CONOCIDO S/N, COLONIA EL PANTEON, SAN FRANCISCO OXTOTILPAN, TEMASCALTEPEC, C.P. 51323", "capacidad" => 0],
            ["id" => 105, "nombre" => "105 TEMASCALTEPEC CENTRO", "municipio_id" => 86, "direccion" => "ITURBIDE #21, COL. CENTRO, TEMASCALTEPEC, C.P. 51300", "capacidad" => 0],
            ["id" => 106, "nombre" => "106 TEXCALTITLÁN", "municipio_id" => 97, "direccion" => "CAMINO REAL ESQ. CARLOS HANK GLZ S/N, SAN AGUSTÍN, TEXCALTITLÁN, C.P. 51675", "capacidad" => 0],
            ["id" => 184, "nombre" => "184 SAN PEDRO LIMON", "municipio_id" => 105, "direccion" => "CARRETERA SAN PEDRO LIMON-ARCELIA S/N , LOC. SAN PEDRO LIMÓN, TLATLAYA, C.P. 51584", "capacidad" => 0],
            ["id" => 107, "nombre" => "107 TLATLAYA CENTRO", "municipio_id" => 105, "direccion" => "C. MIGUEL HIDALGO, COLONIA CENTRO, TLATLAYA, C.P.51550", "capacidad" => 0],
            ["id" => 108, "nombre" => "108 VALLE DE BRAVO CENTRO", "municipio_id" => 110, "direccion" => "C. JOSÉ GUADARRAMA #311, COL. CENTRO, VALLE DE BRAVO, C.P.51230", "capacidad" => 0],
            ["id" => 211, "nombre" => "211 SANTA MARIA AHUACATLAN", "municipio_id" => 110, "direccion" => "AV. SAN VICENTE S/N ESQ. FRAY GREGORIO JIMENEZ , SANTA MARIA AHUACATLAN, VALLE DE BRAVO, C.P.51200", "capacidad" => 0],
            ["id" => 109, "nombre" => "109 ZACAZONAPAN", "municipio_id" => 116, "direccion" => "CALLE VICENTE GUERRERO S/N, COL. CENTRO, ZACAZONAPAN, CP. 51160", "capacidad" => 0],
            ["id" => 202, "nombre" => "202 ZACUALPAN", "municipio_id" => 117, "direccion" => "CALZADA DEL CAMPESINO S/N, BARRIO LA VERACRUZ, ZACUALPAN, C.P. 51800", "capacidad" => 0],
            ["id" => 111, "nombre" => "111 COATEPEC HARINAS", "municipio_id" => 21, "direccion" => "ALVARO OBREGON #16, PRIMERA DE SAN MIGUEL, COATEPEC HARINAS, C.P. 51700", "capacidad" => 0],
            ["id" => 112, "nombre" => "112 IXTAPAN DE LA SAL", "municipio_id" => 40, "direccion" => "CARR IXTAPAN TONATICO SN, BOULEVARO IXTAPAN TONATICO, COL. EL SALITRE, IXTAPAN DE LA SAL, C.P. 51900", "capacidad" => 0],
            ["id" => 113, "nombre" => "113 MALINALCO", "municipio_id" => 52, "direccion" => "C. MIGUEL HIDALGO S/N ENTRE MIGUEL NEGRETE, BARRIO DE SANTA MARIA,, MALINALCO, C.P. 52440", "capacidad" => 0],
            ["id" => 114, "nombre" => "114 RAYÓN", "municipio_id" => 72, "direccion" => "LEONA VICARIO #111, COL. SAN JOSÉ, RAYÓN, C. P. 52360", "capacidad" => 0],
            ["id" => 115, "nombre" => "115 TENANCINGO", "municipio_id" => 88, "direccion" => "ZARAGOZA SUR #107, COL. CENTRO, TENANCINGO, C. P. 52400", "capacidad" => 0],
            ["id" => 116, "nombre" => "116 TENANGO DEL VALLE", "municipio_id" => 90, "direccion" => "CALLE ALVARO OBREGON #300 NTE, ENTRE CALLE PORFIRIO DIAZ Y CONSTITUCIÓN,COL. CENTRO, TENANGO DEL VALLE, C.P. 52300", "capacidad" => 0],
            ["id" => 210, "nombre" => "210 TONATICO", "municipio_id" => 107, "direccion" => "JOSE MARIA MORELOS #42 ESQ. GUADALUPE VICTORIA, BARRIO SANTA MARIA SUR, TONATICO, C.P.51950", "capacidad" => 0],
            ["id" => 118, "nombre" => "118 ZUMPAHUACÁN", "municipio_id" => 119, "direccion" => "AV. ADOLFO LOPEZ MATEOS S/N, BARRIO LA ASCENCION, ZUMPAHUACAN, C.P. 51980", "capacidad" => 0],
            ["id" => 119, "nombre" => "119 VILLA GUERRERO", "municipio_id" => 113, "direccion" => "MARIANO MATAMOROS S/N, COL. CENTRO, VILLA GUERRERO, C.P. 51760", "capacidad" => 0],
            ["id" => 120, "nombre" => "120 JOQUICINGO", "municipio_id" => 49, "direccion" => "VICENTE GUERRERO #7, SEGUNDO BARRIO JOQUICINGO, JOQUICINGO, C.P. 52370", "capacidad" => 0],
            ["id" => 121, "nombre" => "121 SAN PEDRO TEPETITLÁN", "municipio_id" => 2, "direccion" => "CARR TEPEXPAN SN JT KM8 HACIENDA SOBRE CARRETERA , SAN PEDRO TEPETITLAN , ACOLMAN, C.P. 55894", "capacidad" => 0],
            ["id" => 205, "nombre" => "205 ACOLMAN CENTRO", "municipio_id" => 2, "direccion" => "AV. DEL POTRERO ORIENTE #26, CENTRO, ACOLMAN, C.P. 55870", "capacidad" => 0],
            ["id" => 206, "nombre" => "206 LOS ANGELES", "municipio_id" => 2, "direccion" => "FRANCISCO I. MADERO #231, LOS ANGELES, ACOLMAN, C.P.55882", "capacidad" => 0],
            ["id" => 122, "nombre" => "122 AXAPUSCO", "municipio_id" => 16, "direccion" => "VICENTE GUERRERO #4, SAN BARTOLO BAJO, AXAPUSCO, C.P.55940", "capacidad" => 0],
            ["id" => 123, "nombre" => "123 SANTA CATARINA", "municipio_id" => 28, "direccion" => "C. VICTORIA #5, SANTA CATARINA,CHIAUTLA, C.P. 56030", "capacidad" => 0],
            ["id" => 124, "nombre" => "124 SAN LUCAS HUITZILUCAN", "municipio_id" => 28, "direccion" => "DIRECCION 16 DE SEPTIEMBRE S/N, SAN LUCAS HUITZILUCAN,  CHIAUTLA, C.P. 56030", "capacidad" => 0],
            ["id" => 125, "nombre" => "125 NOPALTEPEC", "municipio_id" => 61, "direccion" => "DIRECCION EN BARRIO HIDALGO A, CALLE 5 DE MAYO, MORELOS, NOPALTEPEC, C.P. 55970", "capacidad" => 0],
            ["id" => 126, "nombre" => "126 OTUMBA", "municipio_id" => 65, "direccion" => "FRANCISCO ESPEJEL #16, OTUMBA CENTRO, OTUMBA, C.P. 55900", "capacidad" => 0],
            ["id" => 127, "nombre" => "127 PAPALOTLA", "municipio_id" => 69, "direccion" => "C. VICTORIA #13 ESQ. INSURGENTES Y ALLENDE, BARRIO IXAYOC, PAPALOTLA C.P. 56050", "capacidad" => 0],
            ["id" => 128, "nombre" => "128 SAN MARTÍN DE LAS PIRÁMIDES", "municipio_id" => 75, "direccion" => "VICENTE GUERRERO #2 ,ENTRE CALLE  CASIMIRO LOPEZ MARTINEZ Y 16 DE SEPTIEMBRE ,SAN MARTIN CENTRO,SAN MARTIN DE LAS PIRAMIDES, C.P. 55850", "capacidad" => 0],
            ["id" => 130, "nombre" => "130 TEMASCAPALA", "municipio_id" => 84, "direccion" => "AV. SAN FRANCISCO S/N, TEMASCALAPA CENTRO, TEMASCALAPA, C.P. 55980", "capacidad" => 0],
            ["id" => 131, "nombre" => "131 TEOTIHUACÁN", "municipio_id" => 92, "direccion" => "PALOMAS S/N ESQ. CORRECAMINOS, ATLATONGO, TEOTIHUACAN, C.P. 55816", "capacidad" => 0],
            ["id" => 132, "nombre" => "132 TEPETLAOXTOC", "municipio_id" => 93, "direccion" => "AVENIDA TLAXCANTITLA #26 ENTRE XOLALTENCO Y PZA JUAREZ, CENTRO, TEPETLAOXTOC, C.P. 56070", "capacidad" => 0],
            ["id" => 133, "nombre" => "133 SAN CRISTOBAL NEXQUIPAYAC", "municipio_id" => 11, "direccion" => "C LA PURISIMA ,SAN CRISTOBAL NEXQUIPAYAC, ATENCO C.P 56315", "capacidad" => 0],
            ["id" => 134, "nombre" => "134 SAN SALVADOR ATENCO", "municipio_id" => 11, "direccion" => "C EMILIANO ZAPATA S/N, COL. SAN SALVADOR ATENCO, ATENCO, C.P 56300", "capacidad" => 0],
            ["id" => 135, "nombre" => "135 CHICONCUAC", "municipio_id" => 30, "direccion" => "AV. DEL TRABAJO #4, ENTRE CALLE VERACRUZ A 100 MTS DEL COMPARTAMOS BANCO, COL. LAS JOYAS, CHICONCUAC, C.P 56270", "capacidad" => 0],
            ["id" => 136, "nombre" => "136 SANTA MARIA TECUANULCO", "municipio_id" => 99, "direccion" => "C. PRINCIPAL #190,  ENTRE ZARAGOZA Y HIDALGO, SANTA MARÍA TECUANULCO, TEXCOCO, C.P 56244", "capacidad" => 0],
            ["id" => 137, "nombre" => "137 ZARAGOZA", "municipio_id" => 99, "direccion" => "C. 5 DE MAYO #116,ENTRE PROLONGACION 2 DE MARZO Y CALLE SANTIAGO,  ZARAGOZA, TEXCOCO, C.P 56110 ", "capacidad" => 0],
            ["id" => 139, "nombre" => "139 TEZOYUCA", "municipio_id" => 100, "direccion" => "C. INDEPENDENCIA S/N , COL. SANTIAGO, TEZOYUCA, C.P 56024", "capacidad" => 0],
            ["id" => 140, "nombre" => "140 SAN JUAN IXTACALA", "municipio_id" => 104, "direccion" => "2 DE ABRIL#83, COL. PUEBLO SAN JUAN IXTACALA, TLALNEPANTLA DE BAZ, C.P. 54160", "capacidad" => 0],
            ["id" => 141, "nombre" => "141 DR. JIMENEZ CANTÚ", "municipio_id" => 104, "direccion" => "CERRO IZTLACCIHUATL #71, DR. JORGE JIMENEZ CANTU, TLALNEPANTLA DE BAZ, C.P. 54190", "capacidad" => 0],
            ["id" => 142, "nombre" => "142 SAN ANDRÉS ATENCO", "municipio_id" => 104, "direccion" => "AV. DEL TRABAJO #25, SAN ANDRES ATENCO,TLALNEPANTLA DE BAZ, C.P. 54040", "capacidad" => 0],
            ["id" => 143, "nombre" => "143 CAPULTITLAN", "municipio_id" => 106, "direccion" => "MANUEL BERNAL #8, CAPULTITLÁN, TOLUCA, C.P. 50260 ", "capacidad" => 0],
            ["id" => 144, "nombre" => "144 SAN ANDRES CUEXCONTITLAN", "municipio_id" => 106, "direccion" => "JOSÉ MA. MORELOS Y PAVÓN, SAN ANDRES CUEXCONTITLAN SECC 2,TOLUCA, C.P. 50200", "capacidad" => 0],
            ["id" => 146, "nombre" => "146 SAN LORENZO TEPALTITLÁN", "municipio_id" => 106, "direccion" => "HOMBRES ILUSTRES OTE. #62, SAN LORENZO TEPALTITLÁN, TOLUCA, C.P.50010", "capacidad" => 0],
            ["id" => 147, "nombre" => "147 SAN MATEO OTZACATIPAN", "municipio_id" => 106, "direccion" => "P.º OTZACATIPAN #15, SAN MATEO OTZACATIPAN, TOLUCA, C.P. 50220", "capacidad" => 0],
            ["id" => 145, "nombre" => "145 SAN CAYETANO MORELOS", "municipio_id" => 106, "direccion" => "HÉROES DE LA INDEPENDENCIA MANZANA 001, SAN CAYETANO MORELOS, TOLUCA, C.P. 50295", "capacidad" => 0],
            ["id" => 185, "nombre" => "185 SANTIAGO MILTEPEC", "municipio_id" => 106, "direccion" => "PRIV. MIGUEL HIDALGO #115, SANTIAGO MILTEPEC, TOLUCA, C.P. 50020", "capacidad" => 0],
            ["id" => 186, "nombre" => "186 SEMINARIO 1A SECCION", "municipio_id" => 106, "direccion" => "LAGO WINNIPEG #517, SEMINARIO 1A SECCION, TOLUCA, C.P. 50170", "capacidad" => 0],
            ["id" => 187, "nombre" => "187 SAN JOSÉ GUADALUPE OTZACATIPAN", "municipio_id" => 106, "direccion" => "EMILIANO ZAPATA 843-185, SAN JOSE GUADALUPE OTZACATIPAN, TOLUCA, C.P. 50230", "capacidad" => 0],
            ["id" => 148, "nombre" => "148 U HAB ALBORADA JALTENCO", "municipio_id" => 44, "direccion" => "PENINSULA S/N, U HAB ALBORADA JALTENCO, JALTENCO, C.P. 55783", "capacidad" => 0],
            ["id" => 188, "nombre" => "188 SAN ANDRES JALTENCO", "municipio_id" => 44, "direccion" => "C. LUCAS DOMINGUEZ #8, SAN ANDRES JALTENCO, JALTENCO, C.P. 55780", "capacidad" => 0],
            ["id" => 149, "nombre" => "149 NEXTLALPAN", "municipio_id" => 59, "direccion" => "AVENIDA JUAREZ S/N, BARRIO CENTRAL, NEXTLALPAN, C.P. 55790", "capacidad" => 0],
            ["id" => 189, "nombre" => "189 TONANITLA", "municipio_id" => 125, "direccion" => "MAESTROS S/N, LAS CHINAMPAS, TONANITLA, C.P. 55785", "capacidad" => 0],
            ["id" => 151, "nombre" => "151 TULTEPEC", "municipio_id" => 108, "direccion" => "LEONA VICARIO S/N, BARRIO SAN RAFAEL, TULTEPEC, C.P. 54960", "capacidad" => 0],
            ["id" => 153, "nombre" => "153 BARRIO SANTIAGUITO", "municipio_id" => 109, "direccion" => "AV. MIGUEL HIDALGO Y COSTILLA S/N, BARRIO SANTIAGUITO, TULTITLÁN, C.P. 54900", "capacidad" => 0],
            ["id" => 152, "nombre" => "152 UNIDAD MORELOS 3RA SECCION", "municipio_id" => 109, "direccion" => "CAPRICORNIO Y AV PRADOS NORTE MZ 308 LT2, UNIDAD MORELOS 3RA SECCION, TULTITLÁN, C.P. 54935", "capacidad" => 0],
            ["id" => 154, "nombre" => "154 VALLE DE CHALCO SOLIDARIDAD", "municipio_id" => 122, "direccion" => "PONIENTE 18-A MANZANA 75 LOTE 2, SAN MIGUEL XICO IV, VALLE DE CHALCO SOLIDARIDAD, C.P.56613", "capacidad" => 0],
            ["id" => 155, "nombre" => "155 VILLA DE ALMOLOYA DE JUAREZ", "municipio_id" => 5, "direccion" => "5 DE MAYO S/N, VILLA DE ALMOLOYA DE JUAREZ, ALMOLOYA DE JUAREZ, C.P. 50900", "capacidad" => 0],
            ["id" => 190, "nombre" => "190 VILLA DE ALMOLOYA DE JUAREZ", "municipio_id" => 5, "direccion" => "CAMINO A CABECERA TERCERA SECCION S/N, VILLA DE ALMOLOYA DE JUAREZ, C.P. 50900", "capacidad" => 0],
            ["id" => 156, "nombre" => "156 BARRIO MOLINO ARRIBA", "municipio_id" => 87, "direccion" => "C. CENTRO CEREMONIAL #218, BARRIO MOLINO ARRIBA, TEMOAYA, C.P. 50874", "capacidad" => 0],
            ["id" => 192, "nombre" => "192 MOLINO ARRIBA", "municipio_id" => 87, "direccion" => "CARRETERA CENTRO CEREMONIAL OTOMÍ, MOLINA ARRIBA, TEMOAYA, C.P. 50874", "capacidad" => 0],
            ["id" => 158, "nombre" => "158 SAN LUIS MEXTEPEC", "municipio_id" => 118, "direccion" => "ADOLFO LOPEZ MATEOS #606, SAN LUIS MEXTEPEC, ZINACANTEPEC, C.P. 51355", "capacidad" => 0],
            ["id" => 191, "nombre" => "191 SAN MIGUEL ZINACANTEPEC", "municipio_id" => 118, "direccion" => "IGNACIO LOPEZ RAYON #205, SAN MIGUEL ZINACANTEPEC, ZINACANTEPEC, C.P. 51354", "capacidad" => 0],
            ["id" => 157, "nombre" => "157 SAN ANTONIO ACAHUALCO", "municipio_id" => 118, "direccion" => "CALLE 2 DE ABRIL #151, SAN ANTONIO ACAHUALCO, ZINACANTEPEC, C.P. 51380", "capacidad" => 0],
            ["id" => 159, "nombre" => "159 APAXCO", "municipio_id" => 10, "direccion" => "AV. JUAREZ S/N, COL. CENTRO, APAXCO C.P. 55660", "capacidad" => 0],
            ["id" => 160, "nombre" => "160 CASA NUEVA", "municipio_id" => 35, "direccion" => "C. SOYAMIQUILPAN S/N, COL. CASA NUEVA, HUEHUETOCA, C.P. 54680", "capacidad" => 0],
            ["id" => 161, "nombre" => "161 EL SALITRILLO", "municipio_id" => 35, "direccion" => "BLVD. MARCO ANTONI REYNA S/N, EL SALITRILLO, HUEHUETOCA C.P. 54685", "capacidad" => 0],
            ["id" => 163, "nombre" => "163 CENTENARIO", "municipio_id" => 36, "direccion" => "AV.MIGUEL HIDALGO S/N, COL.CENTENARIO, HUEYPOXTLA, C.P. 55670", "capacidad" => 0],
            ["id" => 162, "nombre" => "162 EL CRUCERO", "municipio_id" => 36, "direccion" => "C. FRANCISCO I MADERO S/N, BARR. EL CRUCERO SANTA MARIA AJOLOAPA, HUEYPOXTLA, C.P. 55679", "capacidad" => 0],
            ["id" => 165, "nombre" => "165 TEQUIXQUIAC", "municipio_id" => 96, "direccion" => "AV. INSURGENTES S/N, COL. CENTRO, TEQUIXQUIAC, C.P. 56650", "capacidad" => 0],
            ["id" => 164, "nombre" => "164 SAN BARTOLO CUAUTLALPAN", "municipio_id" => 120, "direccion" => "AV. DE LOS ANGELES S/N ,COL. SAN BARTOLO CUAUTLALPAN, ZUMPANGO, C.P. 55630", "capacidad" => 0],
            ["id" => 166, "nombre" => "166 SANTA MARIA DE GUADALUPE", "municipio_id" => 120, "direccion" => "DURANGO S/N, COL. SANTA MARIA DE GUADALUPE, ZUMPANGO, C.P.55628", "capacidad" => 0],
            ["id" => 167, "nombre" => "167 PRESIDENTES", "municipio_id" => 29, "direccion" => "CDA. LERDO #5,PRESIDENTES, CHICOLOAPAN, C.P. 56375", "capacidad" => 0],
            ["id" => 168, "nombre" => "168 FRANCISCO VILLA", "municipio_id" => 29, "direccion" => "SAN JUAN DEL RIO MZ 158 LT4 ESQ. CERRADA PACTO DE TORREON, FRANCISCO VILLA, CHICOLOAPAN, C.P. 56390", "capacidad" => 0],

        ];


        foreach ($data as $key => $value) {
            CedisModel::create($value);
        }
    }
}
