<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Programa\Pregunta;

class PreguntasTableSeeder extends Seeder
{
    public function run()
    {
        $preguntas = [

            [
                'id' => 1,
                'programa_id' => 1,
                'numero_pregunta' => '3.1',
                'tipo_pregunta' => 'opcion_unica',
                'pregunta_descripcion' => 'El hogar se encuentra en:',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],
            [
                'id' => 2,
                'programa_id' => 1,
                'numero_pregunta' => '3.2',
                'tipo_pregunta' => 'opcion_unica',
                'pregunta_descripcion' => '¿Cuenta con seguridad social? (Servicios médicos)',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],
            [
                'id' => 3,
                'programa_id' => 1,
                'numero_pregunta' => '3.3',
                'tipo_pregunta' => 'opcion_unica',
                'pregunta_descripcion' => '¿A cuánto ascienden los ingresos mensuales del hogar?',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],
            [
                'id' => 4,
                'programa_id' => 1,
                'numero_pregunta' => '3.4)',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => '¿Es beneficiaria de algún programa social de carácter federal, estatal o municipal?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
            [
                'id' => 5,
                'programa_id' => 1,
                'numero_pregunta' => '',
                'tipo_pregunta' => 'texto_libre',
                'pregunta_descripcion' => '¿Cuál?',
                'requerido' => true,
                'activo' => true,
                'depende_de' => 4,
                'depende_respuesta' => 'si',
            ],
            [
                'id' => 6,
                'programa_id' => 1,
                'numero_pregunta' => '3.5',
                'tipo_pregunta' => 'cantidad_por_opcion',
                'pregunta_descripcion' => 'Parentesco de los dependientes económicos, respecto al jefe del hogar
                (especifique el número de personas en cada caso)',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],
            [
                'id' => 7,
                'programa_id' => 1,
                'numero_pregunta' => '',
                'tipo_pregunta' => 'texto_libre',
                'pregunta_descripcion' => '¿Cuál?',
                'requerido' => true,
                'activo' => true,
                'depende_de' => 6,
                'depende_respuesta' => 'Otro',
            ],
            [
                'id' => 8,
                'programa_id' => 1,
                'numero_pregunta' => '3.6',
                'tipo_pregunta' => 'opcion_unica',
                'pregunta_descripcion' => 'La casa donde vive es:',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],

            [
                'id' => 9,
                'programa_id' => 1,
                'numero_pregunta' => '',
                'tipo_pregunta' => 'texto_libre',
                'pregunta_descripcion' => '¿Cuál?',
                'requerido' => true,
                'activo' => true,
                'depende_de' => 8,
                'depende_respuesta' => 'Otra',
            ],
            [
                'id' => 10,
                'programa_id' => 1,
                'numero_pregunta' => '3.7',
                'tipo_pregunta' => 'opcion_unica',
                'pregunta_descripcion' => '¿Cuántos cuartos tiene su vivienda, contando baños?',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],
            [
                'id' => 11,
                'programa_id' => 1,
                'numero_pregunta' => '3.8',
                'tipo_pregunta' => 'opcion_unica',
                'pregunta_descripcion' => 'Número de personas que viven en su casa:',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],
            [
                'id' => 12,
                'programa_id' => 1,
                'numero_pregunta' => '3.9',
                'tipo_pregunta' => 'opcion_unica',
                'pregunta_descripcion' => '¿De qué material es la mayor parte del piso de esta vivienda?',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],
            [
                'id' => 13,
                'programa_id' => 1,
                'numero_pregunta' => '3.9',
                'tipo_pregunta' => 'opcion_unica',
                'pregunta_descripcion' => '¿De qué material es la mayor parte del techo de esta vivienda?',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],
            [
                'id' => 14,
                'programa_id' => 1,
                'numero_pregunta' => '3.9',
                'tipo_pregunta' => 'opcion_unica',
                'pregunta_descripcion' => '¿De qué material es la mayor parte de las paredes de esta vivienda?',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],

            [
                'id' => 15,
                'programa_id' => 1,
                'numero_pregunta' => '3.10',
                'tipo_pregunta' => 'opcion_multiple',
                'pregunta_descripcion' => '¿Cuáles de estos servicios tiene en su casa? (Selecciona todos los que correspondan)',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],
            [
                'id' => 16,
                'programa_id' => 1,
                'numero_pregunta' => '3.11',
                'tipo_pregunta' => 'opcion_unica',
                'pregunta_descripcion' => '¿Cuál es su grado máximo de estudios?',
                'requerido' => true,
                'activo' => true,
                'depende_de' => null,
                'depende_respuesta' => null,
            ],

            [
                'id' => 17,
                'programa_id' => 1,
                'numero_pregunta' => '',
                'tipo_pregunta' => 'texto_libre',
                'pregunta_descripcion' => '¿Cuál?',
                'requerido' => true,
                'activo' => true,
                'depende_de' => 16,
                'depende_respuesta' => 'Otro',
            ],


            [
                'id' => 18,
                'programa_id' => 1,
                'numero_pregunta' => '4.1',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => '¿Todas las personas que viven en esta vivienda comparten un mismo gasto para comer?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],

            [
                'id' => 19,
                'programa_id' => 1,
                'numero_pregunta' => '4.2',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => 'En los últimos 3 meses, por falta de dinero o recursos ¿alguna vez tuvieron que hacer algo que hubieran
                preferido no hacer para conseguir comida, tal como pedir limosna o mandar a los niños a trabajar?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],

            [
                'id' => 20,
                'programa_id' => 1,
                'numero_pregunta' => '4.3',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => 'En los últimos 3 meses, por falta de dinero o recursos ¿alguna vez el adulto se quedó sin comida?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
            [
                'id' => 21,
                'programa_id' => 1,
                'numero_pregunta' => '4.4',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => 'En los últimos 3 meses, por falta de dinero o recursos ¿alguna vez el adulto sintió hambre pero no comió?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
            [
                'id' => 22,
                'programa_id' => 1,
                'numero_pregunta' => '4.5',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => 'En los últimos 3 meses, por falta de dinero o recursos ¿alguna vez el adulto tuvo una alimentación basada en muy poca variedad de alimentos?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
            [
                'id' => 23,
                'programa_id' => 1,
                'numero_pregunta' => '4.6',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => 'En los últimos 3 meses, por falta de dinero o recursos ¿alguna vez el adulto dejó de desayunar, comer o cenar?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
            [
                'id' => 24,
                'programa_id' => 1,
                'numero_pregunta' => '4.7',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => 'En los últimos 3 meses, por falta de dinero o recursos ¿alguna vez el adulto comió menos de lo que usted piensa que debía comer?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
            [
                'id' => 25,
                'programa_id' => 1,
                'numero_pregunta' => '4.7',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => 'En los últimos 3 meses, por falta de dinero o recursos ¿alguna vez el adulto solo comió una vez al día o dejó de comer todo un día?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
           






            [
                'id' => 32,
                'programa_id' => 1,
                'numero_pregunta' => 'a)',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => '¿Se reconoce como indígena?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
           
            [
                'id'=>34,
                'programa_id' => 1,
                'numero_pregunta' => 'b)',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => '¿Se reconoce como afromexicana?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
           
            [
                'id' => 36,
                'programa_id' => 1,
                'numero_pregunta' => 'c)',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => '¿Se reconoce como parte de la población LGBTQ+?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
            
            [
                'id' => 38,
                'programa_id' => 1,
                'numero_pregunta' => 'd)',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => '¿Tiene alguna enfermedad crónico degenerativa?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
            [
                'id' => 39,
                'programa_id' => 1,
                'numero_pregunta' => 'e)',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => '¿Tiene alguna discapacidad permanente?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
           
            [
                'id' => 41,
                'programa_id' => 1,
                'numero_pregunta' => 'f)',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => '¿Cuida personas con alguna discapacidad?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
           
            [
                'id' => 43,
                'programa_id' => 1,
                'numero_pregunta' => 'g)',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => '¿Ha sido víctima u ofendida de algún delito?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,
            ],
            [
                'id' => 44,
                'programa_id' => 1,
                'numero_pregunta' => 'h)',
                'tipo_pregunta' => 'si_no',
                'pregunta_descripcion' => '¿Es repatriada?',
                'requerido' => true,
                'activo' => true,
                'depende_de'=>null,
                'depende_respuesta'=>null,

            ],
            
        ];

        // Insertar las preguntas en la base de datos
        foreach ($preguntas as $pregunta) {
            Pregunta::create($pregunta);
        }
    }
}
